UPDATE draft site conf 2018 no publised
iv-devs/iv-devs.github.io pull request #37
Opened 2018-04-19 21:53 UTC by cristofer-dev

2018-04-19 22:55 UTC, DMasterIO requested changes

2018-04-19 22:55 UTC, DMaster69 commented on evento2018.html
> +      <h1>IVDevs en números</h1>
le agregaría el espacio onda IV Devs, nunca me ha gustado como queda junto

2018-04-19 22:55 UTC, DMaster69 commented on evento2018.html
> +      <img src="/assets/img/partners/logo_microsoft.png" alt="">
antes de pasarla a master confirmaría este tema, no es menor poner a Microsoft como partner y que no sepan.. prefiero quitarlos

2018-04-19 22:55 UTC, DMaster69 commented on evento2018.html
> +
son: (próximamente || Por Definir || En proceso de...)
La idea es dejar enclaro que viene algo interesante, pero que aún analizamos por eso no quitaría la sección pero si dejaría un "banner" o texto que deje en claro el proceso

2018-04-19 23:12 UTC, cristofer-dev commented on evento2018.html
> +      <img src="/assets/img/partners/logo_microsoft.png" alt="">
Yo lo sacaria!

2018-04-19 23:12 UTC, cristofer-dev commented on evento2018.html
> +
Ok!

2018-04-19 23:12 UTC, cristofer-dev commented
@hpaez @CepheiA @DMaster69 @rodpoblete quien apaña con los cambios ?

2018-04-19 23:16 UTC, DMaster69 commented on evento2018.html
> +      <img src="/assets/img/partners/logo_microsoft.png" alt="">
yo también

2018-04-19 23:17 UTC, DMaster69 commented on evento2018.html
> +
si me haces una imagen bonita que poner ahí, yo mismo saco los cambios

2018-05-05 23:14 UTC, cristofer-dev commented on evento2018.html
> +      <img src="/assets/img/partners/logo_microsoft.png" alt="">
DONE

2018-05-09 00:54 UTC, closed without merging