UPDATE Sponsors plans
iv-devs/iv-devs.github.io pull request #48
Opened 2018-06-17 22:29 UTC by cristofer-dev

Changes to be committed:
	modified:   assets/css/main.css
	modified:   evento2018.html

2018-06-18 02:02 UTC, DMasterIO requested changes

2018-06-18 02:02 UTC, DMaster69 commented on evento2018.html
> +          <div>Nicolas Fernandez</div>
Nico Fernandez nunca fue speaker, en ningún evento

2018-06-18 02:04 UTC, cristofer-dev commented on evento2018.html
> +          <div>Nicolas Fernandez</div>
Ok! Revise la slide de 1er evento y salia! Yo Que se! Falta sumar a los 2017... puedes ?

2018-06-18 14:03 UTC, DMaster69 commented on evento2018.html
> +          <div>Nicolas Fernandez</div>
Claro, es que fue alternativa pero se bajo a última hora. hoy agrego los 2017

2018-06-19 00:38 UTC, cristofer-dev commented
Gracias !! \o

2018-06-21 02:15 UTC, merged